import React from 'react'

function Main() {
  return (
   <>
   <rs-fullwidth-wrap id="rev_slider_3_1_forcefullwidth" style="margin-top:0px;margin-bottom:0px;"><rs-module-wrap id="rev_slider_3_1_wrapper" data-alias="qloud3" data-source="gallery" style="background: transparent; padding: 0px; margin: 0px auto; position: absolute; overflow: visible; width: 1071px; left: 0px; height: 647px;"><rs-module id="rev_slider_3_1" style="height: 647px; max-height: 870px; margin-top: 0px; margin-bottom: 0px;" data-version="6.1.8" data-idcheck="true" class="revslider-initialised rev_redraw_on_blurfocus" data-slideactive="rs-3">
            <rs-slides style="visibility: visible; display: block; max-height: none; height: 100%; width: 100%; overflow: hidden;">
                <rs-slide data-key="rs-3" data-title="Slide" data-anim="ei:d;eo:d;s:1000;r:0;t:fade;sl:0;" data-originalindex="1" data-origindex="0" data-description="" data-sba="" data-scroll-based="false" style="overflow: hidden; height: 100%; width: 100%; z-index: 20; visibility: inherit; opacity: 1;" data-ntrid="0" class="active-rs-slide" data-enterx="640" data-entery="197"><rs-sbg-px style="background-color: rgba(255, 255, 255, 0);"><rs-sbg-wrap style="transform-origin: 50% 50% 0px; opacity: 1; visibility: inherit; top: 0px; left: 0px; transform: matrix(1, 0, 0, 1, 0, 0);"><!--Runtime Modification - Img tag is Still Available for SEO Goals in Source - <img src="revslider/assets/qbanner1.png" alt="QLOUD" title="qbanner1" width="1600" height="867" data-parallax="off" class="rev-slidebg" data-no-retina="">--><rs-sbg src="https://templates.iqonic.design/qloud/html/revslider/assets/qbanner1.png" class="" data-bgcolor="transparent" style="background-color: transparent; background-repeat: no-repeat; background-image: url(&quot;https://templates.iqonic.design/qloud/html/revslider/assets/qbanner1.png&quot;); background-size: cover; background-position: 50% 50%; width: 100%; height: 100%; opacity: 1; top: 0px; left: 0px; visibility: inherit; z-index: 20;" data-src-rs-ref="https://templates.iqonic.design/qloud/html/revslider/assets/qbanner1.png"></rs-sbg></rs-sbg-wrap></rs-sbg-px>
                    
                    <!--
      -->
                    <rs-layer-wrap class="rs-parallax-wrap" style="position: absolute; display: block; pointer-events: auto; left: 100px; top: 175px; z-index: 8; visibility: visible;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; visibility: visible; overflow: visible;"><rs-layer id="slider-3-slide-3-layer-0" class="textgyreadventor rs-layer" data-type="text" data-color="#142149" data-rsp_ch="on" data-xy="xo:135px,96px,72px,15px;y:m;yo:-120px,-85px,-187px,-198px;" data-text="w:normal;s:60,42,36,36;l:80,56,50,45;fw:700;" data-frame_0="x:-50,-35,-26,-16;" data-frame_1="st:600;sp:1000;sR:600;" data-frame_999="o:0;st:w;sR:7400;" style="z-index: 8; visibility: visible; text-align: left; line-height: 59px; letter-spacing: 0px; font-weight: 700; font-size: 45px; border-color: rgb(94, 114, 144); border-style: none; margin: 0px; border-radius: 0px; padding: 0px; color: rgb(20, 33, 73); text-decoration: none; white-space: nowrap; width: auto; height: auto; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;" data-idcheck="true" data-stylerecorder="true" data-initialised="true">Extending <span class="bluetext" data-stylerecorder="true" style="text-align: left; line-height: 59px; letter-spacing: 0px; font-weight: 700; font-size: 45px; border-color: rgb(13, 30, 103); border-style: none; margin: 0px; border-radius: 0px; padding: 0px;">Our Cloud<br>Security</span> Leadership
                    </rs-layer></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap>
                    <!--
      -->
                    <rs-layer-wrap class="rs-parallax-wrap" style="position: absolute; display: block; pointer-events: auto; left: 100px; top: 329px; z-index: 9; visibility: visible;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; visibility: visible; overflow: visible;"><rs-layer id="slider-3-slide-3-layer-1" data-type="text" data-color="#5e7290" data-rsp_ch="on" data-xy="xo:135px,96px,72px,21px;y:m;yo:40px,28px,-78px,-97px;" data-text="w:normal;s:16,11,18,12;l:32,22,30,24;" data-frame_0="x:-50,-35,-26,-16;" data-frame_1="st:900;sp:1000;sR:900;" data-frame_999="o:0;st:w;sR:7100;" style="z-index: 9; visibility: visible; text-align: left; line-height: 24px; letter-spacing: 0px; font-weight: 400; font-size: 12px; border-color: rgb(94, 114, 144); border-style: none; margin: 0px; border-radius: 0px; padding: 0px; color: rgb(94, 114, 144); text-decoration: none; white-space: nowrap; width: auto; height: auto; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;" class="rs-layer" data-idcheck="true" data-stylerecorder="true" data-initialised="true">It is a long established fact that a reader will be distracted by the readable content of
                        <br/>a page when looking at its layout.
                    </rs-layer></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap>
         <rs-layer-wrap class="rs-parallax-wrap" style="position: absolute; display: block; pointer-events: auto; left: 100px; top: 426px; z-index: 10; visibility: visible;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; visibility: visible; overflow: visible;"><a id="slider-3-slide-3-layer-2" class="rs-layer iq-btn-round iq-button rev-btn" href="https://iqonic.design/wp-themes/qloud/contact-us-2/" target="_self" rel="nofollow" data-type="button" data-rsp_ch="on" data-xy="xo:135px,96px,72px,24px;y:m;yo:163px,115px,14px,-11px;" data-text="w:normal;s:18,16,16,16;l:18,16,20,20;" data-dim="h:50px;minh:0px,none,none,none;" data-padding="t:15,15,0,15;r:30;b:15,15,0,15;l:30;" data-border="bor:10px,10px,10px,10px;" data-frame_0="x:-50,-35,-26,-16;" data-frame_1="st:1200;sp:1000;sR:1200;" data-frame_999="o:0;st:w;sR:6800;" data-frame_hover="bgc:#0d1e67;bor:10px,10px,10px,10px;sp:100;e:Power1.easeInOut;bri:120%;" style="z-index: 10; background-color: rgb(0, 123, 252); visibility: visible; text-align: left; line-height: 13px; letter-spacing: 0px; font-weight: 400; font-size: 13px; border-color: rgba(255, 255, 255, 0); border-style: none; margin: 0px; border-radius: 10px; padding: 11px 22px; color: rgb(255, 255, 255); text-decoration: none; white-space: nowrap; width: auto; height: 37px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; filter: blur(0px) grayscale(0%) brightness(100%); opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px; border-width: 0px;" data-idcheck="true" data-stylerecorder="true" data-initialised="true">Read More
      </a></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap>
         
                    <rs-layer-wrap class="rs-parallax-wrap tp-parallax-container" style="position: absolute; display: block; pointer-events: auto; left: 701px; top: 125px; z-index: 12; transform: matrix(1, 0, 0, 1, 0, 0); visibility: visible;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; visibility: visible; overflow: visible;"><rs-layer id="slider-3-slide-3-layer-3" class="rs-pxl-1 rs-layer" data-type="image" data-rsp_ch="on" data-xy="x:r;xo:-146px,-36px,73px,7px;y:m;yo:-27px,67px,84px,81px;" data-text="w:normal;s:20,14,10,6;l:0,17,12,7;" data-dim="w:643px,388px,310px,248px;h:477px,288px,271px,184px;" data-frame_0="sX:0.9;sY:0.9;" data-frame_1="st:2000;sp:1000;sR:2000;" data-frame_999="o:0;st:w;sR:6000;" style="z-index: 12; visibility: visible; overflow: hidden; border-color: rgb(94, 114, 144); border-style: none; margin: 0px; border-radius: 0px; padding: 0px; color: rgb(255, 255, 255); width: 478px; height: 355px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;" data-idcheck="true" data-stylerecorder="true" data-initialised="true"><img src="https://templates.iqonic.design/qloud/html/revslider/assets/b1.png" alt="qloud" width="643" height="477" data-no-retina="" data-src-rs-ref="https://templates.iqonic.design/qloud/html/revslider/assets/b1.png" style="height: 100%; width: 100%; text-align: left; line-height: 19px; letter-spacing: 0px; font-weight: 400; font-size: 12px; border-color: rgb(255, 255, 255); border-style: none; margin: 0px; border-radius: 0px; padding: 0px;" data-stylerecorder="true">
                    </rs-layer></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap>
          
                    <rs-layer-wrap class="rs-parallax-wrap" style="position: absolute; display: block; pointer-events: auto; left: 562px; top: 323px; z-index: 11; visibility: visible;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; visibility: visible; overflow: visible;"><rs-layer id="slider-3-slide-3-layer-4" data-type="image" data-rsp_ch="on" data-xy="x:r;xo:60px,42px,195px,41px;y:b;yo:89px,63px,9px,20px;" data-text="w:normal;s:20,14,10,6;l:0,17,12,7;" data-dim="w:624px,443px,350px,370px;h:346px,246px,190px,201px;" data-frame_0="sX:0.9;sY:0.9;" data-frame_1="st:2500;sp:1000;sR:2500;" data-frame_999="o:0;st:w;sR:5500;" style="z-index: 11; visibility: visible; overflow: hidden; border-color: rgb(94, 114, 144); border-style: none; margin: 0px; border-radius: 0px; padding: 0px; color: rgb(255, 255, 255); width: 464px; height: 257px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;" class="rs-layer" data-idcheck="true" data-stylerecorder="true" data-initialised="true"><img src="https://templates.iqonic.design/qloud/html/revslider/assets/b2.png" alt="qloud" width="624" height="346" data-no-retina="" data-src-rs-ref="https://templates.iqonic.design/qloud/html/revslider/assets/b2.png" style="height: 100%; width: 100%; text-align: left; line-height: 19px; letter-spacing: 0px; font-weight: 400; font-size: 12px; border-color: rgb(255, 255, 255); border-style: none; margin: 0px; border-radius: 0px; padding: 0px;" data-stylerecorder="true"></img>
                    </rs-layer></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap>
          
                    <rs-layer-wrap class="rs-parallax-wrap" style="position: absolute; display: block; pointer-events: auto; left: 237px; top: 426px; z-index: 13; visibility: visible;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; visibility: visible; overflow: visible;"><rs-layer id="slider-3-slide-3-layer-5" data-type="text" data-color="#142149" data-rsp_ch="on" data-xy="xo:320px,250px,235px,184px;y:m;yo:163px,115px,15px,-4px;" data-text="w:normal;s:20,16,16,9;l:50,50,37,22;fw:400,500,500,500;" data-vbility="t,t,t,f" data-frame_0="x:-50,-35,-26,-16;" data-frame_1="st:1600;sp:1000;sR:1600;" data-frame_999="o:0;st:w;sR:6400;" style="z-index: 13; visibility: visible; text-align: left; line-height: 37px; letter-spacing: 0px; font-weight: 400; font-size: 15px; border-color: rgb(94, 114, 144); border-style: none; margin: 0px; border-radius: 0px; padding: 0px; color: rgb(20, 33, 73); text-decoration: none; white-space: nowrap; width: auto; height: auto; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;" class="rs-layer" data-idcheck="true" data-stylerecorder="true" data-initialised="true"><a class="popup-youtube " href="https://www.youtube.com/watch?v=8AZ8GqW5iak" data-stylerecorder="true" style="text-align: left; line-height: 19px; letter-spacing: 0px; font-weight: 400; border-color: rgb(0, 123, 252); border-style: none; margin: 0px; border-radius: 0px; padding: 0px;"><i class="fas fa-play mr-2 bluetext" data-stylerecorder="true" style="text-align: left; letter-spacing: 0px; font-weight: 400; border-color: rgb(13, 30, 103); border-style: none; margin: 0px 6px 0px 0px; border-radius: 0px; padding: 0px;"></i> Watch Video</a>
                    </rs-layer></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap>
        
                    <rs-layer-wrap class="rs-parallax-wrap" style="position: absolute; display: block; pointer-events: auto; left: 100px; top: 516px; z-index: 14; visibility: visible;"><rs-loop-wrap style="position:absolute;display:block;"><rs-mask-wrap style="position: absolute; display: block; visibility: visible; overflow: visible;"><rs-layer id="slider-3-slide-3-layer-6" data-type="text" data-color="#142149" data-rsp_ch="on" data-xy="xo:135px,90px,76px,46px;y:b;yo:150px,170px,222px,136px;" data-text="w:normal;s:18,12,9,5;l:25,17,12,7;" data-dim="h:auto,20px,15px,9px;" data-vbility="t,t,f,f" data-frame_0="x:-50,-35,-26,-16;" data-frame_1="st:2200;sp:1000;sR:2200;" data-frame_999="o:0;st:w;sR:5800;" style="z-index: 14; visibility: visible; text-align: left; line-height: 19px; letter-spacing: 0px; font-weight: 400; font-size: 13px; border-color: rgb(94, 114, 144); border-style: none; margin: 0px; border-radius: 0px; padding: 0px; color: rgb(20, 33, 73); text-decoration: none; white-space: nowrap; width: auto; height: auto; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;" class="rs-layer" data-idcheck="true" data-stylerecorder="true" data-initialised="true"><b data-stylerecorder="true" style="text-align: left; line-height: 19px; letter-spacing: 0px; font-weight: 700; border-color: rgb(20, 33, 73); border-style: none; margin: 0px; border-radius: 0px; padding: 0px;">Free 14-Day Trial -</b> Join over 50,000 websites already using
                    </rs-layer></rs-mask-wrap></rs-loop-wrap></rs-layer-wrap>
     
                </rs-slide>
            </rs-slides>
            <rs-progress class="rs-bottom" style="visibility: hidden !important; width: 0%;"></rs-progress>
        <rs-loader class="spinner0 " style="display: none;"><div class="dot1"></div><div class="dot2"></div><div class="bounce1"></div><div class="bounce2"></div><div class="bounce3"></div></rs-loader></rs-module>
        
        <script>
            if (typeof revslider_showDoubleJqueryError === "undefined") {
                function revslider_showDoubleJqueryError(sliderID) {
                    var err = "<div class='rs_error_message_box'>";
                    err += "<div class='rs_error_message_oops'>Oops...</div>";
                    err += "<div class='rs_error_message_content'>";
                    err += "You have some jquery.js library include that comes after the Slider Revolution files js inclusion.<br>";
                    err += "To fix this, you can:<br>&nbsp;&nbsp;&nbsp; 1. Set 'Module General Options' -> 'Advanced' -> 'jQuery & OutPut Filters' -> 'Put JS to Body' to on";
                    err += "<br>&nbsp;&nbsp;&nbsp; 2. Find the double jQuery.js inclusion and remove it";
                    err += "</div>";
                    err += "</div>";
                    jQuery(sliderID).show().html(err);
                }
            }
        </script>
    </rs-module-wrap><rs-fw-forcer style="height: 647px;"></rs-fw-forcer></rs-fullwidth-wrap>
   </>
  )
}

export default Main